name: CI

on:
  workflow_dispatch:

jobs:
  cache:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: with-crates-toml-crates2-json

      - run: cargo install cargo-expand@1.0.125

  test:
    needs: [cache]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/cache@v6
        with:
          path: |
            ~/.cargo/.crates.toml
            ~/.cargo/.crates2.json
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
          key: with-crates-toml-crates2-json

      - run: cargo install cargo-expand
